version: '3.5'

services:
  dynamo:
    image: amazon/dynamodb-local
    command: '-jar DynamoDBLocal.jar -sharedDb -inMemory'
    networks:
      - backend
    ports:
      - '8000:8000'

networks:
  backend:
    name: lambda-local

